# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86b2a67d04a430c7b962ee14e386b59b7bd6cd16ec53aa34246ac98e0c95838a7be5e63f7e2bdbe6896870ef0d951c4c5e7cfff5a81d28f76b6178ed54dc1a00

test:
  secret_key_base: 0d97b690446973bf700a6d20c9d539156b417644556ab6272bac4c6598e63e7f48479e4804c44c4cdfeef99ee913e5a5d76156ac2376d916023d9141e7404350

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
